sudo: false

cache:
  directories: 
    - node_modules
    - seed/static/vendors/bower_components
    - $HOME/.pip-cache/
    - $HOME/.nvm
    - .tox

language: python

python:
  - 2.7

jdk:
  - oraclejdk8

addons:
  postgresql: '9.4'
  # Sauce credentials in Travis env vars
  sauce_connect: true
  apt_packages:
    - enchant
    - oracle-java8-installer

services:
  - redis-server
  - postgresql
  - cassandra

env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.travis
    - DISPLAY=:99.0
  matrix:
    - TOX_ENV=python
    - TOX_ENV=flake8
    - TOX_ENV=functional
    - TOX_ENV=spelling

install:
  - pip install --upgrade pip
  - pip install tox==2.3.1

before_script:
  - psql -c "create database seeddb;" -U postgres
  - export JAVA_HOME="/usr/lib/jvm/java-8-oracle"
  - export PATH="$PATH:/usr/lib/jvm/java-8-oracle/bin"
  - export java_path="/usr/lib/jvm/java-8-oracle/jre/bin/java"
  - java -version
  - wget https://github.com/kairosdb/kairosdb/releases/download/v1.1.1/kairosdb-1.1.1-1.tar.gz && tar -xvzf kairosdb-1.1.1-1.tar.gz && kairosdb/bin/kairosdb.sh start

script:
  - travis_wait tox -e $TOX_ENV

after_script:
  - coveralls
