language: python

python:
  - 2.7

services:
  - postgresql
  - redis-server

env:
  - DJANGO=1.6.7

before_install:
  - export DJANGO_SETTINGS_MODULE=BE.settings.travis
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

install:
  - pip install -q -e .
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE seeddb;" -U postgres
  - ./bin/install_javascript_dependencies.sh
  - cp BE/settings/local_untracked.py.dist BE/settings/local_untracked.py

script:
  - python manage.py test
  - coverage run manage.py test
  - coverage report -m
