sudo: false

cache:
  directories: 
    - node_modules
    - seed/static/vendors/bower_components
    - $HOME/.pip-cache/

language: python

python:
  - 2.7

addons:
  postgresql: '9.4'

services:
  - redis-server

env:
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.travis
    - DISPLAY=:99.0
  matrix:
    - TOX_ENV=py27-dj18
    - TOX_ENV=flake8

install:
  - pip install --upgrade pip
  - pip install tox==2.3.1

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - psql -c "create database seeddb;" -U postgres

script:
  - tox -e $TOX_ENV

after_script:
  - coveralls
